apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
resources:
  - ../../base
namespace: monitoring
patches:
  - path: replica_count.yaml
  - path: stateful.yaml
  - path: ingress.yaml