apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: velocity-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity-proxy
  template:
    metadata:
      labels:
        app: velocity-proxy
    spec:
      containers:
        - name: velocity-proxy
          image: itzg/mc-proxy
          env:
            - name: BUNGEE_JAR_REVISION
              value: "1"
            - name: REPLACE_ENV_VARIABLES
              value: "true"
            - name: "TYPE"
              value: "VELOCITY"
            - name: "MEMORY"
              value: "1G"
            - name: VELOCITY_BUILD_ID
              value: "555"
            - name: VELOCITY_VERSION
              value: "3.4.0-SNAPSHOT"
            - name: PLUGINS_FILE
              value: "/extras/plugins.txt"
          ports:
            - containerPort: 25565
            - containerPort: 9985
          volumeMounts:
            - name: proxy-data
              mountPath: /server
            - name: proxy-plugins-config
              mountPath: /extras/plugins.txt
              subPath: plugins.txt
      volumes:
        - name: proxy-data
          hostPath:
            path: /opt/minecraft/velocity/data
        - name: proxy-plugins-config
          configMap:
            name: proxy-plugins
