apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lobby-stateful.yaml
  - lobby-svc.yaml

configMapGenerator:
  - name: lobby-config
    envs:
      - lobby.env
  
namespace: minecraft-network