apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bedwars-stateful.yaml
  - bedwars-svc.yaml

configMapGenerator:
  - name: bedwars-plugins
    files:
      - ./plugins.txt
  - name: bedwars-env
    envs:
      - ./.bedwars-env

namespace: minecraft-network