apiVersion: v1
kind: Service
metadata:
  labels:
    service: survie121
  annotations: {}
  # Such as
  #   mc-router.itzg.me/externalServerName: $(EXTERNAL_SERVICE_NAME)
  name: survie121
spec:
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
      nodePort: 30068
    - name: metrics
      port: 9940
      targetPort: 9940
      nodePort: 30988
    - name: voicechat
      port: 31455
      targetPort: 31455
      protocol: UDP
      nodePort: 31455
  type: NodePort
  selector:
    app: survie121