apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']
      - job_name: 'velocity'
        static_configs:
          - targets: ['athena.proxyfil.fr:30985']
            labels:
              proxy_name: 'velocity'
      - job_name: 'minecraft-servers'
        static_configs:
          - targets: ['athena.proxyfil.fr:30986']
            labels:
              server_name: 'public-lobby'
          - targets: ['athena.proxyfil.fr:30987']
            labels:
              server_name: 'bedwars'