apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ntfy-stateful.yaml
  - ntfy-svc.yaml
  - ntfy-ingress.yaml
configMapGenerator:
    - name: server-config
      files: 
        - server.yml
namespace: monitoring